### ISSUE TITLE
Use Gray-Matter for parsing

### ISSUE THREAD

**Issue by RobLoach** [Ajedi32/metalsmith-metafiles#12]
https://www.npmjs.com/package/gray-matter

Abstracts the use of YAML, JSON, TOML, CoffeeScript, CSON, etc.

**Comment by RobLoach** [comment]
Nevermind, I was looking for https://github.com/Ajedi32/metalsmith-matters

**Comment by Ajedi32** [comment]
@RobLoach Which, btw, does in fact use gray-matter for parsing. :wink:
